printWidth: 120
tabWidth: 2
useTabs: true
singleQuote: true

overrides:
  - files:
      - "**/*.yml"
      - "**/*.yaml"
      - "**/*.json"
    options:
      singleQuote: false
      useTabs: false
