import {
	Palmtree,
	Plane,
	Mountain,
	Tent,
	Car,
	Home,
	UtensilsCrossed,
	Beer,
	Pizza,
	Coffee,
	PartyPopper,
	Cake,
	Gift,
	Clapperboard,
	Gamepad2,
	ShoppingCart,
	Hotel,
	Briefcase,
	Music,
	PiggyBank,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

/** Curated line icons for choosing an event's icon. Stored by key in config.icon. */
export const EVENT_ICONS: Record<string, LucideIcon> = {
	beach: Palmtree,
	plane: Plane,
	mountain: Mountain,
	camping: Tent,
	car: Car,
	home: Home,
	dinner: UtensilsCrossed,
	drinks: Beer,
	pizza: Pizza,
	coffee: Coffee,
	party: PartyPopper,
	cake: Cake,
	gift: Gift,
	movie: Clapperboard,
	games: Gamepad2,
	groceries: ShoppingCart,
	hotel: Hotel,
	work: Briefcase,
	music: Music,
	piggy: PiggyBank,
};
