name: Frontend

on:
  pull_request:
    paths:
      - "frontend/**"

permissions:
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Run ESLint
        id: eslint
        run: |
          exitcode=0
          npm run lint --workspace frontend -- -f json -o eslint_report.json || exitcode=$?
          # Ensure we always have a report file, even if ESLint failed
          if [ ! -f eslint_report.json ]; then
            echo "[]" > eslint_report.json
          fi
          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT

      - name: Format ESLint report
        run: node .github/scripts/format-eslint-report.js

      - name: Comment on PR with ESLint report
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: eslint-report
          path: eslint_report.md
          recreate: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fail if linting fails
        if: steps.eslint.outputs.exitcode != 0
        run: exit 1
