name: Lint Check

on:
  pull_request:
    paths:
      - 'frontend/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: cd frontend && npm ci

      - name: Run ESLint
        id: eslint
        run: |
          cd frontend && npm run lint -- -f json -o eslint-report.json
          echo "::set-output name=exitcode::$?"
          echo "Report: $(cat eslint-report.json)"

      - name: Comment on PR with ESLint report
        if: steps.eslint.outputs.exitcode != '0'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: frontend/eslint-report.json